name: Terraform Plan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: cd envs/dev && terraform init

      - name: Terraform plan
        run: cd envs/dev && terraform plan
